name: Build and Deploy Docker Image

on:
  push:
    branches:
      - MOODLE_400_STABLE

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Build Docker image
      run: docker build -t zonemc/moodle2:latest .

    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Push Docker image
      run: docker push zonemc/moodle2:latest

    - name: SSH into AWS Ubuntu machine
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.AWS_HOST }}
        username: ${{ secrets.AWS_USERNAME }}
        key: ${{ secrets.AWS_SSH_PRIVATE_KEY }}

    - name: Pull and Run Docker image on AWS
      run: |
        ssh -i ${{ secrets.AWS_SSH_PRIVATE_KEY }} ${{ secrets.AWS_USERNAME }}@${{ secrets.AWS_HOST }} 'docker pull zonemc/moodle2:latest && docker run -d -p 80:80 zonemc/moodle2:latest'
